var chartData = [
    {
      "myMbti": "ENFP",
      "mbti": [
        "INTJ",
        "INFJ",
        "ENTP",
        "ISFP",
        "ESFP",
        "ENTJ",
        "INFP",
        "ISTJ",
        "ISFJ",
        "ESFJ",
        "ENFJ",
        "ISTP",
        "ESTP",
        "ESTJ",
        "INTP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "INTJ",
      "mbti": [
        "ENFP",
        "ENTP",
        "INFJ",
        "INTP",
        "ENTJ",
        "ISTJ",
        "ISFP",
        "ESFJ",
        "ESFP",
        "ENFJ",
        "ISFJ",
        "ISTP",
        "ESTP",
        "ESTJ",
        "INFP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "INFJ",
      "mbti": [
        "ENFP",
        "INTJ",
        "ENFJ",
        "ENTP",
        "INTP",
        "ISFP",
        "ISTP",
        "ISFJ",
        "ISTJ",
        "ESFJ",
        "ENTJ",
        "ESTP",
        "ESFP",
        "ESTJ",
        "INFP",
        "ISFP"
      ],
      "values": [80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5]
    },
    {
      "myMbti": "ENTP",
      "mbti": [
        "INFJ",
        "INTJ",
        "ENFP",
        "INTP",
        "ENTJ",
        "ISTP",
        "ESFP",
        "ISFP",
        "ISTJ",
        "ISFJ",
        "ENFJ",
        "ESTP",
        "ESFJ",
        "ESTJ",
        "INFP",
        "ISFP"
      ],
      "values": [80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10, 5]
    },
    {
      "myMbti": "ISFJ",
      "mbti": [
        "ESTP",
        "ESFJ",
        "ISTJ",
        "ISFP",
        "ESTJ",
        "INFJ",
        "INTJ",
        "ISTP",
        "ENTP",
        "ENFP",
        "ESFP",
        "ENTJ",
        "ENFJ",
        "INTP",
        "INFP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ESFJ",
      "mbti": [
        "ISFP",
        "ISFJ",
        "ESTJ",
        "ESFP",
        "ESTP",
        "INFJ",
        "ENFJ",
        "ISTP",
        "ENTP",
        "ENFP",
        "ESFP",
        "ENTJ",
        "ENFJ",
        "INTP",
        "INFP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ISTJ",
      "mbti": [
        "ISFJ",
        "ESTJ",
        "INTJ",
        "ISTP",
        "ISFP",
        "ENTJ",
        "INFJ",
        "ENFJ",
        "ENTP",
        "ENFP",
        "ESFP",
        "ESFJ",
        "INFP",
        "INTP",
        "ESTP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ESTJ",
      "mbti": [
        "ISTJ",
        "ESFJ",
        "ENTJ",
        "ESTP",
        "ISTP",
        "ISFJ",
        "ENFJ",
        "INFJ",
        "ENTP",
        "ENFP",
        "ESFP",
        "INTJ",
        "INFP",
        "INTP",
        "ISFP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ISFP",
      "mbti": [
        "ESFJ",
        "ENFP",
        "ESFP",
        "ISTJ",
        "ISFJ",
        "INTP",
        "INFP",
        "ENTP",
        "ENFJ",
        "INFJ",
        "ESTP",
        "ISTP",
        "ENTJ",
        "INTJ",
        "ENFP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ESFP",
      "mbti": [
        "ISFP",
        "ENFP",
        "ESTP",
        "ESFJ",
        "ESTJ",
        "INTP",
        "ENTP",
        "INFJ",
        "ENFJ",
        "ISTJ",
        "ENTJ",
        "ISFJ",
        "ISTP",
        "INFP",
        "INTJ",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ISTP",
      "mbti": [
        "ESTP",
        "INTP",
        "ENTP",
        "ISTJ",
        "ISFP",
        "INTJ",
        "INFP",
        "ENFJ",
        "INFJ",
        "ESFP",
        "ENTJ",
        "ESFJ",
        "ISFJ",
        "ENFP",
        "ESTJ",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ESTP",
      "mbti": [
        "ISFJ",
        "ESFP",
        "ISTP",
        "ESTJ",
        "ENTP",
        "ESFJ",
        "ISFP",
        "ENFP",
        "INFJ",
        "ENTJ",
        "ISTJ",
        "ENFJ",
        "INTJ",
        "INFP",
        "INTP",
        "ISFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "INTP",
      "mbti": [
        "ENTP",
        "INTJ",
        "INFJ",
        "ENTJ",
        "ISTP",
        "ISFP",
        "ENFP",
        "ISFJ",
        "ESFP",
        "ESTJ",
        "ENFJ",
        "ESTP",
        "ISFP",
        "ESFJ",
        "ENFP",
        "INFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ENTJ",
      "mbti": [
        "INTJ",
        "ESTJ",
        "ENTP",
        "INTP",
        "ISFP",
        "INFJ",
        "ENFP",
        "ISTJ",
        "ENFJ",
        "ISFJ",
        "ESFP",
        "ISTP",
        "ESFJ",
        "INFP",
        "ENFP",
        "ENTJ"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "ENFJ",
      "mbti": [
        "INFJ",
        "ENFP",
        "ESFJ",
        "ENTP",
        "ESFP",
        "ISFP",
        "ISTP",
        "INTJ",
        "ENTJ",
        "ISFJ",
        "ISTJ",
        "INFP",
        "INTP",
        "ESTP",
        "ESTJ",
        "ENFJ"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    },
    {
      "myMbti": "INFP",
      "mbti": [
        "ENFP",
        "INFJ",
        "ENFJ",
        "INTJ",
        "ENTP",
        "INTP",
        "ISFP",
        "ENTJ",
        "ISFJ",
        "ESFJ",
        "ISTJ",
        "ESTJ",
        "ISTP",
        "ESTP",
        "ESFP",
        "INFP"
      ],
      "values": [85, 80, 75, 70, 65, 60, 55, 50, 45, 40, 35, 30, 25, 20, 15, 10]
    }
  ]
  